# -*- coding: utf-8 -*-
"""DiccionarioIniciales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dQ8h6PFzm1p-biyIl-08MP33NSlBkxld
"""

lista1=[]
iniciales=[]
dic_iniciales={}
dicci={}
a=0;

n=int(input("Ingresa cuantos elementos componen tu lista: "))

for i in range(0,n,1):
  a=input("Elemento: ")
  a=a.capitalize()  
  lista1.insert(i,a)              #LLENAMOS POSICION A POSICION LOS ELEMENTOS DE LA LISTA
  iniciales.insert(i,a[0])          #LLENAMOS LA LISTA DE INICIALES

dic_iniciales=set(iniciales)        #ELIMINAMOS DUPLICADOS EN LISTA Y HACEMOS DICCIONARIO
iniciales=list(dic_iniciales)       #CONVERTIMOS DE NUEVO A DICCIONARIO

for i in range(0,len(iniciales),1):
  aux2=[]                           #VACIAMOS DICCIONARIO PARA EVITAR QUE SE MEZCLEN RESULTADOS PREVIOS
  aux=[]                            #IGUAL QUE ARRIBA                             
  for j in range(0,n,1):
    if(iniciales[i]==lista1[j][0]):
      aux2=lista1[j]
      aux.append(aux2)
  dicci[iniciales[i]]=aux

print("De la lista de palabras: ")
for i in range(0,n,1):
  print(lista1[i],end=', ')
print(" ")
print(dicci)