# -*- coding: utf-8 -*-
"""Eliminarcaracter&monedas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/118zFrnr1_HrWLpab_v_FTFwI416wtVO1
"""

input_string = input("Write a word: ")
input_charachter = input("Write a charachter: ")

aux = ""
for i in range(0,len(input_string),1):
  if(input_string[i]!=input_charachter):
    aux = aux + input_string[i]
input_string = aux
print("New string: " + input_string)

money = int(input("Write a quantity: "))
ten = 0
five = 0
one = 0
money_aux = money

for i in range(0,money_aux,1):
  if(ten+10<money_aux):
    ten = ten + 10
  else:
    break
money_aux = money_aux - ten

for i in range(0,money_aux,1):
  if(five+5<money_aux):
    five = five + 5
  else:
    break
money_aux = money_aux - five

for i in range(0,money_aux,1):
  if(one+1<=money_aux):
    one = one + 1
  else:
    break
money_aux = money_aux - one

ten = ten / 10
five = five / 5
while(ten>five+1):
  if(five<ten):
    ten = ten - 1
    five = five + 2
      
print("10s: " + str(int(ten)) + " coins")
print("5s: " + str(int(five)) + " coins")
print("1s: " + str(int(one)) + " coins")