# -*- coding: utf-8 -*-
"""listapiroridad.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M47xfq7CPYjOgBbPs7woFbHeUlTGFHZY
"""

from datetime import date, time, datetime
dt = datetime.today()
print(dt)

text = input("Write a word: ")
omit = input("Write a charachter to erase from the previous text: ")

aux = ""
for i in range(0,len(text),1):
  if(text[i].upper()!=omit.upper()):
    aux = aux + text[i]
  
text = aux
print(text)

lista = []
n_listas = int(input("Cuantas listas desea ingresar: "))
for i in range(0,n_listas,1):
  aux = []
  nombre = input("Nombre " + str(i+1) + ": ")
  prioridad = input("Prioridad: ")
  aux.append(prioridad)
  aux.append(nombre)
  lista.insert(i,aux)

lista = sorted(lista,key = itemgetter(0))
print(lista)

from operator import itemgetter
A = [[10, 8], [90, 2], [45, 6]]
print("Sorted List A based on index 0: % s" % (sorted(A, key=itemgetter(0))))
B = [[50, 'Yes'], [20, 'No'], [100, 'Maybe']]
print("Sorted List B based on index 1: % s" % (sorted(B, key=itemgetter(1))))

import random
lista = []
for i in range(0,5,1):
  lista.append(random.randint(0,6))
print(lista)

#Iniciode programa como tal
max = lista[0]
for i in range(0,len(lista),1):
  if(max<lista[i]):
    max = lista[i]

print("El mayor es: " + str(max))

for i in range(0,max,1):
  if(i not in lista):
    print("El elemento más pequeño faltante es: " + str(i))
    break;