# -*- coding: utf-8 -*-
"""Moneda_texto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cUwxUR00xxqa4JYJ8zxPIrI9TfH20l9w
"""

#LIBRERIA DE CIENTOS DE MILES 
def cientos_miles(num,num1,num2):
  if(num==1 and num1==0 and num2==0):
    print("Cien",end=' ')
#  elif((num==1 and num1==0) or (num==1 and num2==0)):
  elif(num==1):
    print("Ciento",end=' ')
  elif(num==2):
    print("Doscientos",end=' ')
  elif(num==3):
    print("Trescientos",end=' ')
  elif(num==4):
    print("Cuatrocientos",end=' ')
  elif(num==5):
    print("Quinientos",end=' ')
  elif(num==6):
    print("Seiscientos",end=' ')
  elif(num==7):
    print("Setescientos",end=' ')
  elif(num==8):
    print("Ochoscientos",end=' ')
  elif(num==9):
    print("Novescientos",end=' ')

#LIBRERIA DE MILES
def miles(num):
  if(num==1):
    print("Mil",end=' ')
  elif(num==2):
    print("Dos mil",end=' ')
  elif(num==3):
    print("Tres mil",end=' ')
  elif(num==4):
    print("Cuatro mil",end=' ')
  elif(num==5):
    print("Cinco mil",end=' ')
  elif(num==6):
    print("Seis mil",end=' ')
  elif(num==7):
    print("Siete mil",end=' ')
  elif(num==8):
    print("Ocho mil",end=' ')
  elif(num==9):
    print("Nueve mil",end=' ')

#LIRERIA DE CIENTOS
def cientos(num):
  if(num==0):
    print("")
  elif(num==1):
    print("Ciento",end=' ')
  elif(num==2):
    print("Doscientos",end=' ')
  elif(num==3):
    print("Trecientos",end=' ')
  elif(num==4):
    print("Cuatrocientos",end=' ')
  elif(num==5):
    print("Quinientos",end=' ')
  elif(num==6):
    print("Seicientos",end=' ')
  elif(num==7):
    print("Setecientos",end=' ')
  elif(num==8):
    print("Ochocientos",end=' ')
  elif(num==9):
    print("Novecientos",end=' ')

#LIRERIA DE DECIMOS
def decimos(num):
  if(num==0):
    print("", end=' ')
  elif(num==1):
    print("Diez",end=' ')
  elif(num==2):
    print("Veinte",end=' ')
  elif(num==3):
    print("Treinta",end=' ')
  elif(num==4):
    print("Cuarenta",end=' ')
  elif(num==5):
    print("Cincuenta",end=' ')
  elif(num==6):
    print("Sesenta",end=' ')
  elif(num==7):
    print("Setenta ",end=' ')
  elif(num==8):
    print("Ochenta",end=' ')
  elif(num==9):
    print("Noventa",end=' ')

#LIRERIA DE UNIDADES
def unidades(num):
  if(num==0):
    print("",end=' ')
  elif(num==1):
    print("Un",end=' ')
  elif(num==2):
    print("Dos",end=' ')
  elif(num==3):
    print("Tres",end=' ')
  elif(num==4):
    print("Cuatro",end=' ')
  elif(num==5):
    print("Cinco",end=' ')
  elif(num==6):
    print("Seis",end=' ')
  elif(num==7):
    print("Siete",end=' ')
  elif(num==8):
    print("Ocho",end=' ')
  elif(num==9):
    print("Nueve",end=' ')

numero=float(input("Ingresa una cantidad: "))
import math
entero=math.trunc(numero)

lon=len(str(entero))

cifras=[]
cifras = [0 for i in range (lon)]

decimal=round((numero-int(entero))*100)

cifras=[]
cifras = [0 for i in range (lon)]

num2=entero
print(numero)
for i in range(0,lon,1):
  residuo=num2%10
  cifras[i]=int(residuo)
  num2=int(num2/10)

#---------------------------------------------------------valor superior a 99999
if(lon==6):
  cientos_miles(cifras[5],cifras[4],cifras[3]) 
  decimos(cifras[4])
  miles(cifras[3])

  if(cifras[4]==0 and cifras[3]==0):
    print("mil",end=' ')

  cientos(cifras[2])
  decimos(cifras[1])
  print("y",end=' ')
  unidades(cifras[0])
  print("pesos MXN",end=' ')

#----------------------------------------------------------valor superior a 9999
elif(lon==5):
  decimos(cifras[4])
  miles(cifras[3])
  cientos(cifras[2])
  decimos(cifras[1])
  print("y",end=' ')
  unidades(cifras[0])
  print("pesos MXN",end=' ')

#-----------------------------------------------------------valor superior a 999
elif(lon==4):
  miles(cifras[3])
  cientos(cifras[2])
  decimos(cifras[1])
  print("y",end=' ')
  unidades(cifras[0])
  print("pesos MXN",end=' ')

#------------------------------------------------------------valor superior a 99
elif(lon==3):
  cientos(cifras[2])
  decimos(cifras[1])
  print("y",end=' ')
  unidades(cifras[0])
  print("pesos MXN",end=' ')

#-------------------------------------------------------------valor superior a 9
elif(lon==2):
  decimos(cifras[1])
  print("y",end=' ')
  unidades(cifras[0])
  print("pesos MXN",end=' ')

#-------------------------------------------------------------valor menor o igual a 9
elif(lon==1):
  unidades(cifras[0])
  print("pesos MXN",end=' ')

else:
  print("La cantidad ingresada es demasiado grande o incorrecta, intente de nuevo")

conversion=decimal/10
cifras2=[0,0]

cifras2[0]=math.trunc(conversion)
cifras2[1]=int((conversion-cifras2[0])*10)

if(decimal!=0):
  print("con",end=' ')
  decimos(cifras2[0])
  unidades(cifras2[1])
  print("centavos")